"""Domain models and reusable infrastructure abstractions."""

# Configure Pillow before importing any model that opens an image.
from . import image_limits as _image_limits  # noqa: F401

from .abstractions import (
    DirectoryIndexer,
    DirectoryScanner,
    DistanceMetric,
    FileAnalyzer,
    ImageDirectoryScanner,
    IndexedFile,
    NaturalPathOrderer,
    PathOrderer,
    RecursiveDirectoryIndexer,
    RecursiveDirectoryScanner,
)
from .image_duplicates import (
    DeduplicationOptions,
    DirectoryDeduplicator,
    Duplicate,
    DuplicateDetector,
    FileRemover,
    ImageSignature,
    ImageSignatureDistance,
    LocalFileRemover,
    PillowImageSignatureAnalyzer,
    ReverseDuplicateDetector,
    deduplicate_directory,
    find_duplicates,
    hamming_distance,
    image_signature,
    index_images,
    perceptual_hash,
)
from .image_webp import (
    DecodedImage,
    PillowWebPCodec,
    WebPCodec,
    WebPConversion,
    WebPDirectoryConverter,
    WebPOptions,
    WebPSkip,
    convert_directory_to_webp,
)
from .path_sort import path_number_key, sort_numbered_paths

__all__ = [
    "DecodedImage",
    "DeduplicationOptions",
    "DirectoryDeduplicator",
    "DirectoryIndexer",
    "DirectoryScanner",
    "DistanceMetric",
    "Duplicate",
    "DuplicateDetector",
    "FileAnalyzer",
    "FileRemover",
    "ImageDirectoryScanner",
    "ImageSignature",
    "ImageSignatureDistance",
    "IndexedFile",
    "LocalFileRemover",
    "NaturalPathOrderer",
    "PathOrderer",
    "PillowImageSignatureAnalyzer",
    "PillowWebPCodec",
    "RecursiveDirectoryIndexer",
    "RecursiveDirectoryScanner",
    "ReverseDuplicateDetector",
    "WebPCodec",
    "WebPConversion",
    "WebPDirectoryConverter",
    "WebPOptions",
    "WebPSkip",
    "convert_directory_to_webp",
    "deduplicate_directory",
    "find_duplicates",
    "hamming_distance",
    "image_signature",
    "index_images",
    "path_number_key",
    "perceptual_hash",
    "sort_numbered_paths",
]