"""Public API and executable entry point for cleanup-cli."""

from collections.abc import Sequence

from .models import (
    DecodedImage,
    DeduplicationOptions,
    DirectoryDeduplicator,
    DirectoryIndexer,
    DirectoryScanner,
    DistanceMetric,
    Duplicate,
    DuplicateDetector,
    FileAnalyzer,
    FileRemover,
    ImageDirectoryScanner,
    ImageSignature,
    ImageSignatureDistance,
    IndexedFile,
    LocalFileRemover,
    NaturalPathOrderer,
    PathOrderer,
    PyAVImageSignatureAnalyzer,
    PyAVWebPCodec,
    RecursiveDirectoryIndexer,
    RecursiveDirectoryScanner,
    ReverseDuplicateDetector,
    WebPCodec,
    WebPConversion,
    WebPDirectoryConverter,
    WebPOptions,
    WebPSkip,
    convert_directory_to_webp,
    deduplicate_directory,
    find_duplicates,
    hamming_distance,
    image_signature,
    index_images,
    path_number_key,
    perceptual_hash,
    sort_numbered_paths,
)
from .controllers import (
    Controller,
    DeduplicationController,
    DeduplicationRequest,
    DeduplicationResult,
    WebPConversionController,
    WebPConversionRequest,
    WebPConversionResult,
)
from .views import ArgparseCliView, CliView, create_cli_view


__all__ = [
    "ArgparseCliView",
    "CliView",
    "Controller",
    "Duplicate",
    "DuplicateDetector",
    "DeduplicationOptions",
    "DeduplicationController",
    "DeduplicationRequest",
    "DeduplicationResult",
    "DirectoryDeduplicator",
    "DirectoryIndexer",
    "DirectoryScanner",
    "DistanceMetric",
    "DecodedImage",
    "FileAnalyzer",
    "FileRemover",
    "ImageDirectoryScanner",
    "ImageSignature",
    "ImageSignatureDistance",
    "IndexedFile",
    "LocalFileRemover",
    "NaturalPathOrderer",
    "PathOrderer",
    "PyAVImageSignatureAnalyzer",
    "PyAVWebPCodec",
    "RecursiveDirectoryIndexer",
    "RecursiveDirectoryScanner",
    "ReverseDuplicateDetector",
    "WebPCodec",
    "WebPConversion",
    "WebPConversionController",
    "WebPConversionRequest",
    "WebPConversionResult",
    "WebPDirectoryConverter",
    "WebPOptions",
    "WebPSkip",
    "convert_directory_to_webp",
    "create_cli_view",
    "deduplicate_directory",
    "find_duplicates",
    "hamming_distance",
    "image_signature",
    "index_images",
    "main",
    "path_number_key",
    "perceptual_hash",
    "sort_numbered_paths",
]


def main(arguments: Sequence[str] | None = None) -> int:
    """Run the default command-line view."""

    return create_cli_view().run(arguments)
